blog/urls.py
from django.urls import path, include

from contact.forms import ContactForm
from .views import home, CommentCreateView
from .views import PostListView, PostDetailView, UserDetailView, UserListView, AboutView, UserUpdateView, \
	UserPostListView, CustomLogoutView, UserProfileView, LoginViewForm, home
from blog.views import LoginViewForm, RegisterView
from blog.views import PostCreate, PostUpdate, LogoutView, LoginViewForm, CategoryListView, TagList, TagDetailView, CategoryDetailView
from django.conf import settings
from contact.views import ContactViewMain

app_name = "blog"

urlpatterns = [

	path('', home, name='home'),
	path("about/", AboutView.as_view(), name="about"),

	path('login/', LoginViewForm.as_view(), name='login'),
	path('logout/', CustomLogoutView.as_view(), name='logout'),
	path("register/", RegisterView.as_view(), name="register"),

	path("profile/<str:username>/", UserDetailView.as_view(), name="user_profile"),
	path("profile/<slug:username>/update/", UserUpdateView.as_view(), name='user_update'),

	path("users/", UserListView.as_view(), name="user_list"),
	path('user/<str:username>/', UserDetailView.as_view(), name='user_detail'),

	path("create/", PostCreate.as_view(), name="post_create"),
	path("post/<slug:slug>/", PostDetailView.as_view(), name="post_detail"),
	path('post/<slug:slug>/update/', PostUpdate.as_view(), name='post_update'),

	path('post/<slug:slug>/comment/', CommentCreateView.as_view(), name='add_comment'),

	path('myposts/<str:username>/', UserPostListView.as_view(), name='user_posts'),

	path("category/", CategoryListView.as_view(), name='category_list'),
	path("category/<str:name>", CategoryDetailView.as_view(), name='category_detail'),

	path("tags/", TagList.as_view(), name='tag_list'),
	path("tags/<str:name>", TagDetailView.as_view(), name='tag_detail'),

	path('contact/', ContactViewMain.as_view(), name='contact'),
	# path("success/", success_view, name="success"),
]

if settings.DEBUG:
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_zerotohero/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = "Blog Project"
admin.site.index_title = "Hillel IT School"

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('markdown_editor/', include('markdown_editor.urls')),
    path(r'mdeditor/', include('mdeditor.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),

    # path("login/", LoginView.as_view(), name="login"),
    # path('logout/', CustomLogoutView.as_view(), name="logout"),
    # path("register/", RegisterView.as_view(), name="register"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.urls import reverse
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractUser
from martor.models import MartorField
from django.db import models
from django.utils.text import slugify
from mdeditor.fields import MDTextField


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=255)
    body = MDTextField(null=True, blank=True)
    short_description = models.CharField(max_length=255, blank=True, null=True)
    categories = models.ManyToManyField(Category, related_name="posts")
    tags = models.ManyToManyField("Tag")
    author = models.ForeignKey("UserProfile", related_name='blog_posts', on_delete=models.CASCADE)
    slug = models.SlugField(max_length=250, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    publish = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to="images/")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        verbose_name = "Blog Posts"
        verbose_name_plural = "Blog Posts"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class UserProfile(AbstractUser):
    full_name = models.CharField(max_length=255, blank=True)
    development = models.CharField(max_length=100, blank=True)
    email = models.EmailField()
    avatar = models.ImageField(upload_to="avatar/", blank=True, null=True)
    gender = models.CharField(max_length=1, choices=(('M', 'Male'), ('F', 'Female'), ('N', 'None')))
    age = models.IntegerField(null=True)
    biography = models.TextField(null=True, blank=True)
    website = models.URLField(blank=True)
    location = models.CharField(max_length=30, blank=True)
    mobile = models.CharField(max_length=20, null=True, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)
    github = models.URLField(blank=True)
    twitter = models.URLField(blank=True)
    instagram = models.URLField(blank=True)
    facebook = models.URLField(blank=True)

    def get_absolute_url(self):
        return f"/user/{self.username}"


class Comments(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments_post")
    body = models.TextField(blank=True)
    email = models.EmailField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    published = models.BooleanField(default=False)

    class Meta:
        ordering = ["created"]
        verbose_name = "Blog Comments"
        verbose_name_plural = "Blog Comments"

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.post)


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from django.contrib.auth.views import LoginView
from blog.models import UserProfile, Category, Post
from blog.models import Comments
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from mdeditor.fields import MDTextField


class PostForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Post
        fields = ['title', 'body', 'categories', 'tags', 'image', 'status']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["mobile", "address", "age", "gender", "biography", "location", "website", "avatar"]


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = UserProfile
        fields = ["mobile", "address", "age", "gender", "biography", "location", "website", "avatar", "development"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ["body"]

# class ScheduleEmailForm(forms.Form):
#     # name = forms.CharField(label='Name', max_length=100)
#     # email = forms.EmailField(label='Email', max_length=100)
#     # subject = forms.CharField(label='Subject', max_length=100)
#     # message = forms.CharField(label='Message', widget=forms.Textarea)
#     # date = forms.DateTimeField(label='Date and Time', input_formats=['%Y-%m-%dT%H:%M'], widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
#
#     def send_email(self, date):
#         # name = [self.cleaned_data['name']]
#         # email = self.cleaned_data['email']
#         # subject = self.cleaned_data['subject']
#         # message = self.cleaned_data['message']
#         # date_at = self.cleaned_data['date']
#         send_feedback_email_task.apply_async(**date)

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100)
    email = forms.EmailField(label='Email')
    subject = forms.ChoiceField(label='Subject', choices=[
        ('feedback', 'Feedback'),
        ('bug_report', 'Report a bug'),
        ('feature_request', 'Feature request'),
        ('other', 'Other'),
    ])
    message = forms.CharField(label='Message', widget=forms.Textarea)

blog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views import generic, View
from django.views.generic import DetailView, TemplateView, ListView, CreateView
from django.views.generic import FormView
from django.views.generic import UpdateView
from django.views.generic.edit import FormMixin
from django.core.paginator import Paginator
from django.shortcuts import render

from .forms import CommentForm

from accounts.forms import RegisterForm
from .models import Post, Category, Tag, Comments
from .models import UserProfile


def home(request):
    category_list = Category.objects.all()
    post_list = Post.objects.all()
    tag_list = Tag.objects.all()
    posts_per_page = 5
    paginator = Paginator(post_list, posts_per_page)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "category_list": category_list,
        "post_list": post_list,
        "page_obj": page_obj,
        "tag_list": tag_list,
    }
    return render(request, "blog/home.html", context)


class LoginViewForm(FormView):
    form_class = AuthenticationForm
    template_name = "blog/login.html"
    success_message = "Login successful"
    success_url = reverse_lazy("blog:home")
    error_message = "Login False!"

    def form_valid(self, form):
        # We log the user in and redirect to the home page.
        user = form.get_user()
        login(self.request, user)
        return super().form_valid(form)


class CustomLogoutView(LogoutView):
    template_name = 'blog/logout.html'


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = "blog/register.html"
    success_message = "Registration successful"
    success_url = reverse_lazy("blog:home")
    error_message = "Registration False!"

    def form_valid(self, form):
        user = form.save()
        user = authenticate(self.request, username=user.username, password=form.cleaned_data.get("password1"))
        login(self.request, user)
        return super(RegisterView, self).form_valid(form)


# class HomePageView(ListView):
#     model = Post
#     context_object_name = "home"
#     template_name = "blog/home.html"
#
#     def get_queryset(self):
#         return Post.objects.order_by('-created')

class CategoryListView(generic.ListView):
    model = Category
    context_object_name = "category_list"
    template_name = "blog/category_list.html"


class CategoryDetailView(generic.DetailView):
    model = Category
    context_object_name = "category_detail"
    template_name = "blog/category_detail.html"

    def get_object(self, queryset=None):
        name = self.kwargs.get("name")
        return get_object_or_404(Category, name=name)


class TagList(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "blog/tag_list.html"


class TagDetailView(generic.DetailView):
    model = Tag
    context_object_name = "tag_detail"
    template_name = 'blog/tag_detail.html'

    def get_object(self, queryset=None):
        name = self.kwargs.get("name")
        return get_object_or_404(Tag, name=name)


class PostListView(generic.ListView):
    model = Post
    context_object_name = "post_list"
    paginate_by = 4
    template_name = "blog/post_list.html"


# class CommentCreateView(LoginRequiredMixin, generic.CreateView):
#     model = Comments
#     form_class = CommentForm
#     template_name = 'blog/comment_form.html'
#     success_url = reverse_lazy('post_list')
#
#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         post = Post.objects.get(slug=self.kwargs['slug'])
#         form.instance.post = post
#         response = super().form_valid(form)
#         messages.success(self.request, 'Comment added.')
#         return response


class PostDetailView(generic.DetailView, LoginRequiredMixin, FormMixin):
    # Handle user's input from form
    form_class = CommentForm
    model = Post
    context_object_name = "post_detail"
    paginate_by = 4
    slug_field = "slug"
    # slug_url_kwarg = "slug"
    success_message = "Comment added"
    template_name = "blog/post_detail.html"

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    # Add comment to the db
    def form_valid(self, form):
        # Crete instance of the comment, but don't save
        self.object = form.save(commit=False)
        self.object.post = self.get_object()
        self.object.user = self.request.user
        self.object.body = form.cleaned_data['body']
        self.object.save()
        return super().form_valid(form)

    # Get all comments filtered by Post
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_detail"] = self.get_object()
        comments = Comments.objects.filter(post=self.object, published=True).order_by("created")
        context["comments"] = comments
        return context

    def get_success_url(self):
        return reverse_lazy("blog:post_detail", kwargs={"slug": self.kwargs['slug']})


class PostCreate(LoginRequiredMixin, generic.CreateView):
    model = Post
    context_object_name = "post_create"
    template_name = "blog/post_create.html"
    fields = ["title", "body", "short_description", "categories", "tags", "image", "status"]
    success_url = reverse_lazy("blog:post_detail")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        from django.urls import reverse
        return reverse("blog:post_detail", kwargs={"slug": self.object.slug})


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    context_object_name = "post_update"
    template_name = "blog/post_update.html"
    fields = ["title", "body", "tags", "image"]
    success_message = "Post updated"

    def get_success_url(self):
        return reverse_lazy("blog:post_detail", kwargs={"slug": self.object.slug})


class CommentCreateView(LoginRequiredMixin, CreateView):
    pass
    # model = Comments
    # form_class = CommentForm
    # template_name = "blog/comment_form.html"
    # success_message = "Comment added"
    # slug_url_kwarg = "slug"
    #
    # def form_valid(self, form):
    #     form.instance.user = self.request.user
    #     form.instance.post = get_object_or_404(Post, slug=self.kwargs['slug'])
    #     return super().form_valid(form)
    #
    # def get_success_url(self):
    #     return reverse_lazy("blog:post_detail", kwargs={"slug": self.kwargs["slug"]})


class UserListView(generic.ListView):
    model = UserProfile
    context_object_name = "user_list"
    paginate_by = 4
    template_name = "blog/user_list.html"


class UserDetailView(DetailView):
    model = UserProfile
    context_object_name = "user_detail"
    template_name = "blog/user_detail.html"

    def get_object(self, queryset=None):
        username = self.kwargs.get("username")
        return get_object_or_404(UserProfile, username=username)


class UserProfileView(LoginRequiredMixin, DetailView):
    model = UserProfile
    template_name = 'blog/user_profile.html'


class UserPostListView(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = "user_posts"
    template_name = "blog/user_posts.html"
    paginate_by = 4

    def get_queryset(self):
        username = self.request.user
        return Post.objects.filter(author=username).order_by("-created")


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = UserProfile
    context_object_name = "user_update"
    template_name = "blog/user_update.html"
    slug_field = "username"
    slug_url_kwarg = "username"
    fields = ["full_name", "email", "mobile", "address", "age", "gender", "biography", "location", "website"]
    success_message = "Profile Updated"

    def get_success_url(self):
        username = self.object.username
        return reverse_lazy("blog:user_profile", kwargs={"username": username})


class AboutView(TemplateView):
    template_name = "blog/about.html"

templates/blog/category_list.html
        {% for category in category_list %}
            <a href="{{ category.slug }}" class="badge badge-secondary mr-2 mb-2">{{ category.slug }}</a>
          {% endfor %}

templates/blog/comment_create.html
<section>
  <p class="text-center"><strong>Leave a reply</strong></p>
  <form method="post" action="{% url 'blog:add_comment' post.slug %}">
    {% csrf_token %}
    <!-- Name input -->
    <div class="form-outline mb-4">
      <input type="text" name="name" id="id_name" class="form-control" required />
      <label class="form-label" for="id_name">Name</label>
    </div>

    <!-- Email input -->
    <div class="form-outline mb-4">
      <input type="email" name="email" id="id_email" class="form-control" required />
      <label class="form-label" for="id_email">Email address</label>
    </div>

    <!-- Message input -->
    <div class="form-outline mb-4">
      <textarea class="form-control" name="message" id="id_message" rows="4" required></textarea>
      <label class="form-label" for="id_message">Text</label>
    </div>

    <!-- Checkbox -->
    <div class="form-check d-flex justify-content-center mb-4">
      <input class="form-check-input me-2" type="checkbox" name="send_copy" value="1" id="form4Example4" checked />
      <label class="form-check-label" for="form4Example4">
        Send me a copy of this comment
      </label>
    </div>

    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">
      Publish
    </button>
  </form>
</section>

templates/blog/password_reset_done.html
{% extends 'blog/base.html' %}
{% load bootstrap_icons %}
{% load static %}

{% block content %}
  <p>We've emailed you instructions for setting your password. If they haven't arrived in a few minutes, check your spam folder.</p>
{% endblock %}

templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load bootstrap_icons %}
{% load static %}
{% block content %}
    {% csrf_token %}

    <div id="intro" class="p-5 text-center bg-light">
      <h1 class="mb-0 h4">{{ post_detail.title }}</h1>
    </div>
     <!--Main layout-->
  <main class="mt-4 mb-5">
    <div class="container">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-md-8 mb-4">
          <!--Section: Post data-mdb-->
          <section class="border-bottom mb-4">
           {% if post_detail.image %}
           <img class="img-fluid shadow-2-strong rounded-5 mb-4" src="{{ post_detail.image.url }}" alt="{{ post_detail.title }}">
           {% endif %}

            <div class="row align-items-center mb-4">
              <div class="col-lg-6 text-center text-lg-start mb-3 m-lg-0">
                <img src="{{ post_detail.author.avatar.url }}" class="rounded-5 shadow-1-strong me-2"
                  height="35" alt="" loading="lazy" />
                <span> Published <u>{{ post_detail.created|date:"F d, Y" }}</u> by</span>
                <a href="{% url 'blog:user_detail' username=post_detail.author.username %}" class="text-dark">{{ post_detail.author.username }}</a>
              </div>

              <div class="col-lg-6 text-center text-lg-end">
                <button type="button" class="btn btn-primary px-3 me-1" style="background-color: #3b5998;">
                  <i class="fab fa-facebook-f"></i>
                </button>
                <button type="button" class="btn btn-primary px-3 me-1" style="background-color: #55acee;">
                  <i class="fab fa-twitter"></i>
                </button>
                <button type="button" class="btn btn-primary px-3 me-1" style="background-color: #0082ca;">
                  <i class="fab fa-linkedin"></i>
                </button>
                <button type="button" class="btn btn-primary px-3 me-1">
                  <i class="fas fa-comments"></i>
                </button>
              </div>
            </div>
          </section>
          <!--Section: Post data-mdb-->

                 <!--Section: Text-->
          <section>
            <p>
                {{ post_detail.short_description }}
            </p>

            <p><strong>{{ post_detail.title }}</strong></p>

            <p>{{ post_detail.body|linebreaks }}
            </p>
          </section>
          <!--Section: Text-->

                <!--Section: Share buttons-->
          <section class="text-center border-top border-bottom py-4 mb-4">
            <p><strong>Share with your friends:</strong></p>

            <button type="button" class="btn btn-primary me-1" style="background-color: #3b5998;">
              <i class="fab fa-facebook-f"></i>
            </button>
            <button type="button" class="btn btn-primary me-1" style="background-color: #55acee;">
              <i class="fab fa-twitter"></i>
            </button>
            <button type="button" class="btn btn-primary me-1" style="background-color: #0082ca;">
              <i class="fab fa-linkedin"></i>
            </button>
            <button type="button" class="btn btn-primary me-1">
              <i class="fas fa-comments me-2"></i>Add comment
            </button>
          </section>
          <!--Section: Share buttons-->

                <!--Section: Author-->
          <section class="border-bottom mb-4 pb-4">
            <div class="row">
              <div class="col-2">
                <img src="{{ post_detail.author.avatar.url }}" class="img-fluid shadow-2-strong rounded-6" alt="" />
              </div>

              <div class="col-9">
                <p class="mb-2"><strong>{{ post_detail.author }}</strong></p>
                <a href="" class="text-dark"><i class="fab fa-facebook-f me-1"></i></a>
                <a href="" class="text-dark"><i class="fab fa-twitter me-1"></i></a>
                <a href="" class="text-dark"><i class="fab fa-linkedin me-1"></i></a>
                <p>
                    {{ post_detail.author.biography }}
                </p>
              </div>
            </div>
          </section>
          <!--Section: Author-->



  <div class="container my-2 py-2">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 col-lg-12">
        <div class="card text-dark">
          <div class="card-body p-4">

            <h4 class="mb-0">Recent comments</h4>
          {% if comments.exists %}
            <p class="fw-light mb-4 pb-2">
                {% with comments.count as total_comments %}
                Total: {{ total_comments }} comment{{ total_comments|pluralize }}
                {% endwith %}
            {% else %}
    <p class="fw-light mb-4 pb-2">
        No comments yet
    </p>
{% endif %}
              </p>


<div class="d-flex flex-start">
              <div>
{% for comment in comments %}
<div class="blockquote mb-4">
  <div class="d-flex align-items-center justify-content-between">
      {% if comment.user.avatar.url %}
      <img src="{{ comment.user.avatar.url }} " class="rounded-2 shadow-2-strong me-2"   height="45" width="45" alt="" loading="lazy" />&rarr;
      {% endif %}
    <h6 class="fw-bold mb-1">{{ comment.user.full_name }} </h6>
    <p class="mb-0">
      {{ comment.created }}
      <span class="badge bg-primary">{{ comment.published }}</span>
    </p>
  </div>
  <hr class="my-2">
  <p class="mb-1" style="font-size: 18px">{{ comment.body }}</p>
</div>
{% endfor %}

                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



{# Old comments#}
{#    <div class="card mt-4">#}
{#        <div class="card-header">#}
{#            <h4>Comments ({{ post_detail.comments }})</h4>#}
{#        </div>#}
{#        <div class="card-body">#}
{#            {% for comment in post_detail.comments.all %}#}
{#                <div class="media mb-4">#}
{#             {% if post_detail.author.avatar %}#}
{#            <img class="rounded-circle"#}
{#              src="{{ post_detail.author.avatar.url }}" alt="{{ post_detail.author.username }}"#}
{#              style="width: 45px; height: 45px"#}
{#            />#}
{#            {% endif %}#}
{#                    <div class="media-body">#}
{#                        <h5 class="mt-0">{{ comment.user.get_full_name }}</h5>#}
{#                        <p>{{ comment.body }}</p>#}
{#                        <small class="text-muted">{{ comment.created|date:'F d, Y' }}</small>#}
{#                    </div>#}
{#                </div>#}
{#            {% empty %}#}
{#                <p>There are no comments yet.</p>#}
{#            {% endfor %}#}
{#        </div>#}
{#    </div>#}


<!--Section: Comment Reply-->
          <section>
            <p class="text-center"><strong>Leave a reply</strong></p>
              <form action="." method="post">
    {% csrf_token %}
    <div class="form-outline mb-4">
        <textarea class="form-control" id="body" name="body" rows="4"></textarea>
        <label class="form-label" for="body">Text</label>
    </div>
    <button type="submit" class="btn btn-primary btn-block mb-4">Publish</button>
</form>

{#            <form action="." method="post">#}
{#                {% csrf_token %}#}
{#              <!-- Name input -->#}
{#              <div class="form-outline mb-4">#}
{#                <input type="text" id="id_name" class="form-control" />#}
{#                <label class="form-label" for="id_name">Name</label>#}
{#              </div>#}
{##}
{#              <!-- Email input -->#}
{#              <div class="form-outline mb-4">#}
{#                <input type="email" id="id_email" class="form-control" />#}
{#                <label class="form-label" for="id_email">Email address</label>#}
{#              </div>#}

              <!-- Message input -->
{#              <div class="form-outline mb-4">#}
{#                <textarea class="form-control" id="body" rows="4"></textarea>#}
{#                <label class="form-label" for="body">Text</label>#}
{#              </div>#}

{#              <!-- Checkbox -->#}
{#              <div class="form-check d-flex justify-content-center mb-4">#}
{#                <input class="form-check-input me-2" type="checkbox" value="" id="form4Example4" checked />#}
{#                <label class="form-check-label" for="form4Example4">#}
{#                  Send me a copy of this comment#}
{#                </label>#}
{#              </div>#}

              <!-- Submit button -->
{#              <button type="submit" class="btn btn-primary btn-block mb-4">#}
{#                Publish#}
{#              </button>#}
{#            </form>#}
          </section>
          <!--Section: Reply-->
        </div>
        <!--Grid column-->

{% include 'blog/sidebar.html' %}

    <!--Footer-->
  <footer class="bg-light text-lg-start">
    <div class="py-4 text-center">
      <a role="button" class="btn btn-primary btn-lg m-2"
        href="https://www.youtube.com/channel/UC5CF7mLQZhvx8O5GODZAhdA" rel="nofollow" target="_blank">
        Learn Bootstrap 5
      </a>
      <a role="button" class="btn btn-primary btn-lg m-2" href="https://mdbootstrap.com/docs/standard/" target="_blank">
        Download MDB UI KIT
      </a>
    </div>

    <hr class="m-0" />

    <div class="text-center py-4 align-items-center">
      <p>Follow MDB on social media</p>
      <a href="https://www.youtube.com/channel/UC5CF7mLQZhvx8O5GODZAhdA" class="btn btn-primary m-1" role="button"
        rel="nofollow" target="_blank">
        <i class="fab fa-youtube"></i>
      </a>
      <a href="https://www.facebook.com/mdbootstrap" class="btn btn-primary m-1" role="button" rel="nofollow"
        target="_blank">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="https://twitter.com/MDBootstrap" class="btn btn-primary m-1" role="button" rel="nofollow"
        target="_blank">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="https://github.com/mdbootstrap/mdb-ui-kit" class="btn btn-primary m-1" role="button" rel="nofollow"
        target="_blank">
        <i class="fab fa-github"></i>
      </a>
    </div>
  </footer>
      </div>
    </div>
  </main>
{% endblock %}

templates/blog/tag_list.html
{% for tag in tag_list %}
<a href="{{ tag.name }}" class="badge badge-secondary mr-2 mb-2">{{ tag.name }}</a>
{% endfor %}