blog/urls.py
from django.urls import path, include

from contact.forms import ContactForm
from .views import home, CommentCreateView
from .views import PostListView, PostDetailView, UserDetailView, UserListView, AboutView, UserUpdateView, \
	UserPostListView, CustomLogoutView, UserProfileView, LoginViewForm, home
from blog.views import LoginViewForm, RegisterView
from blog.views import PostCreate, PostUpdate, LogoutView, LoginViewForm, CategoryListView, TagList, TagDetailView, CategoryDetailView
from django.conf import settings
from contact.views import ContactViewMain

app_name = "blog"

urlpatterns = [

	path('', home, name='home'),
	path("about/", AboutView.as_view(), name="about"),

	path('login/', LoginViewForm.as_view(), name='login'),
	path('logout/', CustomLogoutView.as_view(), name='logout'),
	path("register/", RegisterView.as_view(), name="register"),

	path("profile/<str:username>/", UserDetailView.as_view(), name="user_profile"),
	path("profile/<slug:username>/update/", UserUpdateView.as_view(), name='user_update'),

	path("users/", UserListView.as_view(), name="user_list"),
	path('user/<str:username>/', UserDetailView.as_view(), name='user_detail'),

	path("create/", PostCreate.as_view(), name="post_create"),
	path("post/<slug:slug>/", PostDetailView.as_view(), name="post_detail"),
	path('post/<slug:slug>/update/', PostUpdate.as_view(), name='post_update'),

	path('post/<slug:slug>/comment/', CommentCreateView.as_view(), name='add_comment'),

	path('myposts/<str:username>/', UserPostListView.as_view(), name='user_posts'),

	path("category/", CategoryListView.as_view(), name='category_list'),
	path("category/<str:name>", CategoryDetailView.as_view(), name='category_detail'),

	path("tags/", TagList.as_view(), name='tag_list'),
	path("tags/<str:name>", TagDetailView.as_view(), name='tag_detail'),

	path('contact/', ContactViewMain.as_view(), name='contact'),
	# path("success/", success_view, name="success"),
]

if settings.DEBUG:
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_zerotohero/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = "Blog Project"
admin.site.index_title = "Hillel IT School"

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('markdown_editor/', include('markdown_editor.urls')),
    path(r'mdeditor/', include('mdeditor.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),

    # path("login/", LoginView.as_view(), name="login"),
    # path('logout/', CustomLogoutView.as_view(), name="logout"),
    # path("register/", RegisterView.as_view(), name="register"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.urls import reverse
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractUser
from martor.models import MartorField
from django.db import models
from django.utils.text import slugify
from mdeditor.fields import MDTextField


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=255)
    body = MDTextField(null=True, blank=True)
    short_description = models.CharField(max_length=255, blank=True, null=True)
    categories = models.ManyToManyField(Category, related_name="posts")
    tags = models.ManyToManyField("Tag")
    author = models.ForeignKey("UserProfile", related_name='blog_posts', on_delete=models.CASCADE)
    slug = models.SlugField(max_length=250, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    publish = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to="images/")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        verbose_name = "Blog Posts"
        verbose_name_plural = "Blog Posts"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class UserProfile(AbstractUser):
    full_name = models.CharField(max_length=255, blank=True)
    development = models.CharField(max_length=100, blank=True)
    email = models.EmailField()
    avatar = models.ImageField(upload_to="avatar/", blank=True, null=True)
    gender = models.CharField(max_length=1, choices=(('M', 'Male'), ('F', 'Female'), ('N', 'None')))
    age = models.IntegerField(null=True)
    biography = models.TextField(null=True, blank=True)
    website = models.URLField(blank=True)
    location = models.CharField(max_length=30, blank=True)
    mobile = models.CharField(max_length=20, null=True, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)
    github = models.URLField(blank=True)
    twitter = models.URLField(blank=True)
    instagram = models.URLField(blank=True)
    facebook = models.URLField(blank=True)

    def get_absolute_url(self):
        return f"/user/{self.username}"


class Comments(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments_post")
    body = models.TextField(blank=True)
    email = models.EmailField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    published = models.BooleanField(default=False)

    class Meta:
        ordering = ["created"]
        verbose_name = "Blog Comments"
        verbose_name_plural = "Blog Comments"

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.post)


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

templates/form.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}{{ title }} :: {{ block.super }}{% endblock %}

{% block css %}
  <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'martor/css/martor.bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock %}

{% block content %}
  <form class="form" method="post">{% csrf_token %}
    <div class="form-group">
      {{ form.title }}
    </div>
    <div class="form-group">
      {{ form.description }}
    </div>
    <div class="form-group">
      {{ form.wiki }}
    </div>
    <div class="form-group">
      <button class="btn btn-success">
        <i class="save icon"></i> Save Post
      </button>
    </div>
  </form>
{% endblock %}

{% block js %}
  <script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/typo.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/spellcheck.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'martor/js/martor.bootstrap.min.js' %}"></script>

  <script>
    $('form [name="title"]').attr({
      'class': 'form-control',
      'placeholder': 'Post Title'
    });
  </script>
{% endblock %}

templates/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load bootstrap_icons %}


<h1>Login</h1>
{% block content %}
{#<form method="post" action="{% url 'blog:login' %}">#}
{#{% csrf_token %}#}
{#<section class="vh-80">#}
{#  <div class="container-fluid h-custom">#}
{#    <div class="row d-flex justify-content-center align-items-center h-80">#}
{#      <div class="col-md-9 col-lg-6 col-xl-5">#}
{#        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"#}
{#          class="img-fluid" alt="Sample image">#}
{#      </div>#}
{#      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">#}
{#          <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">#}
{#            <p class="lead fw-normal mb-0 me-3">Sign in with</p>#}
{#            <button type="button" class="btn btn-primary btn-floating mx-1">#}
{#              <i class="fab fa-facebook-f"></i>#}
{#            </button>#}
{##}
{#            <button type="button" class="btn btn-primary btn-floating mx-1">#}
{#              <i class="fab fa-twitter"></i>#}
{#            </button>#}
{##}
{#            <button type="button" class="btn btn-primary btn-floating mx-1">#}
{#              <i class="fab fa-linkedin-in"></i>#}
{#            </button>#}
{#          </div>#}
{##}
{#          <div class="divider d-flex align-items-center my-4">#}
{#            <p class="text-center fw-bold mx-3 mb-0">Or</p>#}
{#          </div>#}
{##}
{#          <!-- Email input -->#}
{#          <div class="form-outline mb-4">#}
{#            <input type="email" id="id_email" name="email" class="form-control form-control-lg"#}
{#              placeholder="Enter a valid email address" />#}
{#            <label class="form-label" for="id_email">Email address</label>#}
{#          </div>#}
{##}
{#          <!-- Password input -->#}
{#          <div class="form-outline mb-3">#}
{#            <input type="password" id="id_password" name="password" class="form-control form-control-lg"#}
{#              placeholder="Enter password" />#}
{#            <label class="form-label" for="id_password">Password</label>#}
{#          </div>#}
{##}
{#          <div class="d-flex justify-content-between align-items-center">#}
{#            <!-- Checkbox -->#}
{#            <div class="form-check mb-0">#}
{#              <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />#}
{#              <label class="form-check-label" for="form2Example3">#}
{#                Remember me#}
{#              </label>#}
{#            </div>#}
{#            <a href="#!" class="text-body">Forgot password?</a>#}
{#          </div>#}
{##}
{#          <div class="text-center text-lg-start mt-4 pt-2">#}
{#             <button type="submit" class="btn btn-primary btn-lg"#}
{#              style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>#}
{#            <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{% url "blog:register" %}"#}
{#                class="link-danger">Register</a></p>#}
{#          </div>#}
{#</div>#}
{#    </div>#}
{#  </div>#}
{#</section>#}
{#    </form>#}


        <div class="content-section">
        <form method="post" action="{% url 'blog:login' %}">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Log In</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Do you need account? <a class="ml-2" href="{% url 'blog:register' %}">Register</a>
            </small>
        </div>
    </div>
{% endblock %}

templates/test_markdownify.html
{% extends "blog/base.html" %}
{% load static %}
{% load martortags %}
{% block title %}Test Markdonify :: {{ block.super }}{% endblock %}

{% block css %}
  <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'martor/css/martor.bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock %}

{% block content %}
  <div class="martor-content">
    <h3>Title: {{ post.title }}</h3>
    <p><b>Description:</b></p>
    <hr />
    <div class="martor-preview">
      {{ post.description|safe_markdown }}
    </div>
  </div>
{% endblock %}

{% block js %}
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script>
    $('.martor-preview pre').each(function(i, block){
        hljs.highlightBlock(block);
    });
  </script>
{% endblock %}